FROM postgres:15

WORKDIR /docker-entrypoint-initdb.d/

RUN apt-get update && apt-get install -y curl

RUN curl -o db_script.sql https://raw.githubusercontent.com/OsalexRod/arquitectura/master/db_script.sql
