FROM maven:3.9 AS constructor

WORKDIR /usr/src/mymaven/

RUN git clone https://github.com/OsalexRod/arquitectura.git && \
    cd ./arquitectura && \
    mvn compile && \
    mvn package
#RUN mvn clean package

FROM tomcat:9

WORKDIR /usr/local/tomcat/webapps/

ENV DB_HOST=""
ENV DB_PORT=""
ENV DB_DATABASE=""
ENV DB_USERNAME=""
ENV DB_PASSWORD=""

COPY --from=constructor /usr/src/mymaven/arquitectura/target/arquitectura.war ./ROOT.war
