version: '2.15'

services:
  arquitectura:
    container_name: arquitectura
    build:
      context: .
      dockerfile: ./Dockerfile.diplomado
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgresdb
      DB_PORT: 5432
      DB_DATABASE: diplomado
      DB_USERNAME: postgres
      DB_PASSWORD: 123456

  postgresdb:
    container_name: postgresdb
    image: alejandrorodriguezsalazar/postgresdb:4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: diplomado
  
  adminer:
    container_name: adminer
    image: adminer:4
    restart: always
    ports:
      - "8081:8080"
